######################################################################
# Automatically generated by qmake (3.0) Wed Nov 28 17:43:05 2012
######################################################################

TEMPLATE = app
QT += core gui
TARGET = gTail
DEPENDPATH += . release
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
RESOURCES += application.qrc
