#############################################################################
# Makefile for building: gTail
# Generated by qmake (3.0) (Qt 5.0.0) on: Sun Dec 2 10:03:01 2012
# Project:  gTail.pro
# Template: app
# Command: C:\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\bin\qmake.exe -spec win32-msvc2010 -o Makefile gTail.pro
#############################################################################

first: release
install: release-install
uninstall: release-uninstall
MAKEFILE      = Makefile
QMAKE         = C:\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: gTail.pro ..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\win32-msvc2010\qmake.conf ..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\spec_pre.prf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\common\shell-win32.conf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\qconfig.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_activeqt.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_clucene.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_core.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_declarative.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_designer.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_designercomponents.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_help.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_network.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_platformsupport.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_qml.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_qmldevtools.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_qtmultimediaquicktools.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_quick.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_quickparticles.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_script.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_scripttools.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_svg.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_uitools.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_v8.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_webkitwidgets.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\qt_functions.prf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\qt_config.prf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\win32-msvc2010\qmake.conf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\spec_post.prf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\exclusive_builds.prf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\default_pre.prf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\win32\default_pre.prf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\release.prf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\debug_and_release.prf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\default_post.prf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\shared.prf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\win32\rtti.prf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\warn_on.prf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\qt.prf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\resources.prf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\moc.prf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\win32\opengl.prf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\win32\thread.prf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\win32\windows.prf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\exceptions.prf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\yacc.prf \
		..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\lex.prf \
		gTail.pro \
		C:/Qt/sdk/Qt5.0.0beta2/5.0.0-beta2/msvc2010/lib/libEGL.prl \
		C:/Qt/sdk/Qt5.0.0beta2/5.0.0-beta2/msvc2010/lib/libGLESv2.prl
	$(QMAKE) -spec win32-msvc2010 -o Makefile gTail.pro
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\spec_pre.prf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\common\shell-win32.conf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\qconfig.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_activeqt.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_clucene.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_core.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_declarative.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_designer.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_designercomponents.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_gui.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_help.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_network.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_platformsupport.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_qml.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_qmldevtools.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_qtmultimediaquicktools.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_quick.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_quickparticles.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_script.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_scripttools.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_sql.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_svg.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_v8.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_webkitwidgets.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_xml.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\qt_functions.prf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\qt_config.prf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\win32-msvc2010\qmake.conf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\spec_post.prf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\exclusive_builds.prf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\default_pre.prf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\win32\default_pre.prf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\release.prf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\debug_and_release.prf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\default_post.prf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\shared.prf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\win32\rtti.prf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\warn_on.prf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\qt.prf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\resources.prf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\moc.prf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\win32\opengl.prf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\win32\thread.prf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\win32\windows.prf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\exceptions.prf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\yacc.prf:
..\..\..\..\..\Qt\sdk\Qt5.0.0beta2\5.0.0-beta2\msvc2010\mkspecs\features\lex.prf:
gTail.pro:
C:/Qt/sdk/Qt5.0.0beta2/5.0.0-beta2/msvc2010/lib/libEGL.prl:
C:/Qt/sdk/Qt5.0.0beta2/5.0.0-beta2/msvc2010/lib/libGLESv2.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2010 -o Makefile gTail.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
	-$(DEL_FILE) gTail.exp
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile

check: first

docs:

install_docs:

uninstall_docs:

release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
